[package]
name = "usch"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.9", features = [ "derive" ] }
cpal = "0.13"
egui = { version = "0.17", optional = true }
egui_wgpu_backend = { version = "0.17", optional = true }
egui_winit_platform = { version = "0.14", optional = true }
futures = "0.3"
lazy_static = "1.4"
lewton = { version = "0.10", optional = true }
notify = { version = "4.0", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
shaderc = "0.8"
wgpu = { version = "0.12", features = ["spirv"] }
winit = "0.26"

[features]
default = ["editor", "ogg"]
editor = ["hot-reload", "ui", "dep:serde", "dep:serde_json"]
hot-reload = ["dep:notify"]
ogg = ["dep:lewton"]
ui = ["dep:egui", "dep:egui_wgpu_backend", "dep:egui_winit_platform"]
